<?php

namespace Venissieux\InventaireSDB\FrontBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository {

    
    /**
     * Recherche des articles par critère
     * @param type $data
     * @param type $page
     * @param type $max
     * @param type $sortColumn
     * @param type $sortDirection
     * @param type $disponibleOnly
     * @param type $listeArticlesAExclure
     * @param type $listeArticlesAInclure
     * @param type $getResult
     * @return type
     */
    public function search($data, $page = 0, $max = NULL, $sortColumn = null, $sortDirection = null, $disponibleOnly = false, $listeArticlesAExclure = null, $listeArticlesAInclure = null, $getResult = true) {
        $qb = $this->_em->createQueryBuilder();
        $query = isset($data['query']) && $data['query'] ? $data['query'] : null;

        $qb
                ->select('a')
                ->from('VenissieuxInventaireSDBFrontBundle:Article', 'a');


        //Filtre sur les articles disponibles (aucune occurence de prets avec une date de retour vide)
        if ($disponibleOnly) {
            $sub = $this->_em->createQueryBuilder();
            $sub->select('p');
            $sub->from('VenissieuxInventaireSDBFrontBundle:Pret', 'p');
            $sub->andWhere('p.article = a');
            $sub->andWhere('p.dateRetour is null');

            //Ajout de la condition (imbrication de la sous requête exists avec la requête initiale)
            $qb->andWhere($qb->expr()->not($qb->expr()->exists($sub->getDQL())));
        }

        //Filtre sur les articles à exclure (création d'une clause NOT IN)
        if (!empty($listeArticlesAExclure)) {
            $qb->andWhere('a.id NOT IN (:listeArticlesAExclure)')
                    ->setParameter('listeArticlesAExclure', $listeArticlesAExclure);
        }

        //Filtre sur les articles à inclure (création d'une clause IN en dehors des articles disponibles)
        if (!empty($listeArticlesAInclure)) {
            $qb->orWhere('a.id IN (:listeArticlesAInclure)')
                    ->setParameter('listeArticlesAInclure', $listeArticlesAInclure);
        }
        
        
        //Ajout d'un tri si demandé
        if (isset($sortColumn) && isset($sortDirection)) {
            $qb->orderBy('a.' . $sortColumn, $sortDirection);
        }

        
        //Filtre sur le critère de recherche (nom, commentaire, id)
        if ($query) {

            $queryCriteria = 'UPPER(a.nom) like UPPER(:query) OR UPPER(a.commentaire) like UPPER(:query)';

            //Si la valeur recherchée est un entier, on ajoute une recherche sur l'id de l'article
            if (ctype_digit($query)) {
                $queryCriteria = $queryCriteria . ' OR a.id = :queryInt';
            }

            $qb->andWhere($queryCriteria);
            $qb->setParameter('query', "%" . $query . "%");
            
            if (ctype_digit($query)) {
                $qb->setParameter('queryInt', (int) $query);
            }
        }

        //Filtre de pagination
        if ($max) {
            $preparedQuery = $qb->getQuery()
                    ->setMaxResults($max)
                    ->setFirstResult($page * $max)
            ;
        } else {
            $preparedQuery = $qb->getQuery();
        }

        return $getResult ? $preparedQuery->getResult() : $preparedQuery;
    }

}
